<?php

$t = array(

    'Developer by Abdulaziz' => 'Developer by Abdulaziz',
    'home_page'      => 'Home',
    'Show_Orders'    => 'Show Orders',
    'sr'             => 'Services',
    'Log_out'        => 'Log out',
    'Log_in'         => 'Log in',
    'registration'   => 'Registration',
    'My_Profile'     => 'My Profile',
    'Edit_My_Profile'=> 'Edit My Profile',
    'Quick_Service'  => 'Quick Service',
    'Normal_Service'         => 'Normal Service',
    'Price:_10RS'            => 'Price: 10RS',
    'Available_on_24_hours'  => 'Available on 24 hours',
    'Pay_on_delivery'        => 'Pay on delivery',
    'No_price'               => 'No price',
    'Our_Services'           => 'Our Services',
    'The_category'           => 'Categories',
    'The_subcategory_of_Clothes'                    => 'Subcategories of Clothes',
    'The_subcategory_of_Carpets'                    => 'Subcategories of Carpets',
    'The_subcategory_of_Blankets_and_Sheets'        => 'Subcategories of Blankets and Sheets',
    'Prayer_Carpets'        => 'Prayer Carpets',
    'Prayer_Sheets'         => 'Prayer Sheets',
    'Doormat_Carpets'       => 'Doormat Carpets',
    'Table_cloth'           => 'Table Cloth',
    'Long_or_Short_Carpets' => 'Long or Short Carpets',
    'Long_or_Short_blanket_of_bed' => 'Long or Short blanket of bed',

    'Name_Of_Client'        => 'Name Of Client in English',
    'Name_Of_laundryWorker' => 'Name Of laundry Worker',
    'Name_Of_Admin'         => 'Name Of Admin',
    'Name_Of_Driver'        => 'Name Of driver',
    'Email_Address'         => 'Email Address',
    'Birth_Date'            => 'Birthday Date',
    'Phone_Number'          => 'Phone Number',
    'Password'              => 'Password',

    'Your_name'                => 'Your Name',
    'Your_Email_Address'       => 'Your Email Address',
    'Your_Birth_Date'          => 'Your Birth Date',
    'Your_Phone_Number'        => 'Your Phone Number',
    'Your_Password'            => 'Your Password',
    'Edit'                     => 'Edit',
    'Email_of_Client'          => 'Email of Client',
    'Email_of_LW'              => 'Email of Laundry Worker',
    'Email_of_A'               => 'Email of Admin',
    'Email_of_D'               => 'Email of Driver',
    'Enter_your_email'         => 'Enter your email',
    'Enter_your_password'      => 'Enter your password',


    'User_not_found'               => 'User not found',
    'You_can\'t_leave_any_or_all'  => 'You can\'t leave any or all',
    'fields_blank'                 => 'fields blank',

    'register'                    => 'Register',
    'Register_is'                 => 'The register is',
    'Done_and_Successfully'       => 'Done and Successfully',
    'Enter_Your_Phone_Number'     => 'Enter your phone number',
    'Enter_Your_birthday_date'    => 'Enter your birthday date',
    'Enter_your_confirm_password' => 'Enter your confirm password',
    'Enter_Your_name'             => 'Enter your name',
    'Confirm_password'            => 'Confirm Password',
    'page'                        => 'Page',

    'Client_Show_Order'         => 'Client Show Orders',
    'Admin_Show_Order'          => 'Admin Show Orders',
    'LaundryWorker_Show_Order'  => 'Laundry Worker Show Orders',
    'Driver_Show_Order'         => 'Driver Show Orders',
    'ID'                        => 'ID',
    'Date'                      => 'Date',
    'Status'                    => 'Status',
    'Show'                      => 'Show',
    'Client_Name'               => 'Client Name',

    'Order_Details'                         => ' Client Order Details',
    'AOrder_Details'                        => ' Admin Order Details',
    'LWOrder_Details'                       => ' Laundry Worker Order Details',
    'DOrder_Details'                        => ' Driver Order Details',
    'Order_ID:'                             => 'Order ID:',
    'Order_Date:'                           => 'Order Date:',
    'The_service:'                          => 'The service:',
    'The_category:'                         => 'The category:',
    'The_subcategory:'                      => 'The subcategory: ',
    'The_type_of_service:'                  => 'The type of service:',
    'Delivery_Price:'                       => 'Delivery Price:',
    'Order_Timeline'                        => 'Order Timeline',
    'Total_Order_Price_without_Vat:'        => 'Total Order Price without Vat:',
    'Total_Order_Price_with_Vat:'           => 'Total Order Price with Vat:',
    'Vat_Price:'                            => 'Vat Price:',
    'Status:'                               => 'Status:',
    '(Price: 5 RS)'                         => '(Price: 5 RS)',
    '(Price: 10 RS)'                        => '(Price: 10 RS)',
    'Change_Status:'                        => 'Change Status:',
    'There_is_a_problem,_please_try_again'  => 'There is a problem, please try again',
    'Client'                                => 'Client',
    'Admin'                                 => 'Admin',
    'Laundry_Worker'                        => 'Laundry Worker',
    'Driver'                                => 'Driver',
    'RS'                                    => 'RS',
    'We can not found this service!'        => 'We can not found this service!',
    'We can not found this category!'       => 'We can not found this category!',
    'We can not found Order Timeline!'      => 'We can not found Order Timeline!',
    'We can not found this order!'          => 'We can not found this order!',
    'We can not found Subcategory!'         => 'We can not found Subcategory!',
    'Back_to_orders_page'                   => 'Back to orders page',

    'Request_Service'                       => 'Request Service',
    'Select_The_service:'                   => 'Select The service:',
    'Select_The_category:'                  => 'Select the category:',
    'Next'                                  => 'Next',
    'You can not cancel your order now'     => 'You can not cancel your order now',
    '(Price:'                               => '(Price:',
    'RS)'                                   => 'RS)',
    'Qty'                                   => 'Quantity is',

    'White_Thob'                            => 'White Thob',
    'Color_Thob'                            => 'Color Thob',
    'Under_Shirt'                           => 'Under Shirt',
    'Sport_Suit'                            => 'Sport Suit',
    'Shemagh'                               => 'Shemagh',
    'Pajama'                                => 'Pajama',
    'School_Dress'                          => 'School Dress',
    'Suit'                                  => 'Suit',
    'Jacket'                                => 'Jacket',
    'Sock'                                  => 'Sock',
    'Moroccan_Thob'                         => 'Moroccan Thob',

    'Shirt'                                 => 'Shirt',
    'Trouser'                               => 'Trouser',
    'Jens'                                  => 'Jens',
    'Farwa'                                 => 'Farwa',
    'Cap'                                   => 'Cap',
    'Coat'                                  => 'Coat',
    'Pullover'                              => 'Pullover',
    'Dress'                                 => 'Dress',
    'Gutra'                                 => 'Gutra',
    'Abbaya'                                => 'Abbaya',
    'Bath_Robe'                             => 'Bath Robe',
    'Tarha'                                 => 'Tarha',
    'Basht'                                 => 'Basht',

    'Add_New_Category'                      => 'Add New Category',
    'Show Categories'                       => 'Show Categories',
    'Add new driver'                        => 'Add new driver',
    'Show drivers'                          => 'Show drivers',
    'Add new laundry worker'                => 'Add new laundry worker',
    'Show laundry workers'                  => 'Show laundry workers',
    'Add new service'                       => 'Add new service',
    'Show services'                         => 'Show services',
    'Add Subcategory'                       => 'Add Subcategory',
    'Show Subcategories'                    => 'Show Subcategories',

    'Picture of Category'                     => 'Picture of Category',
    'Picture of Service'                      => 'Picture of Service',
    'Enter Picture of service'                => 'Enter Picture of service',
    'Name of Category'                        => 'Name of Category in English',
    'Name of Subcategory'                     => 'Name of Subcategory in English',
    'Name of Service'                         => 'Name of Service in English',
    'Name of Driver'                          => 'Name of Driver in English',
    'Name_of_Laundry_Worker'                  => 'Name of Laundry Worker in English',
    'Enter Picture of category'               => 'Enter Picture of category',
    'Enter name of category'                  => 'Enter name of category',
    'Enter name of subcategory'               => 'Enter name of subcategory',
    'Enter name of service'                   => 'Enter name of service',
    'Enter name of driver'                    => 'Enter name of driver',
    'Enter name of laundry worker'            => 'Enter name of laundry worker',
    'The'                                     => 'The',
    'category is Added'                       => 'category is Added',
    'driver is Added'                         => 'driver is Added',
    'laundry worker is Added'                 => 'laundry worker is Added',
    'subcategory is Added'                    => 'subcategory is Added',
    'service is Added'                        => 'service is Added',
    'category is already'                     => 'category is already',
    'driver is already'                       => 'driver is already',
    'laundry worker is already'               => 'laundry worker is already',
    'subcategory is already'                  => 'subcategory is already',
    'service is already'                      => 'service is already',
    'Successfully'                            => 'Successfully',
    'Exist'                                   => 'Exist',
    'Something wrong try again!'              => 'Something wrong try again!',
    'The Picture can not upload try again!'   => 'The Picture can not upload try again!',
    'All fields have (*) required!'            => 'All fields have (*) required!',

    'Name_Of_laundryWorker_in_arabic'         => 'Name of laundryWorker in arabic',
    'Name_Of_driver_in_arabic'                => 'Name of driver in arabic',
    'Name_Of_category_in_arabic'              => 'Name of category in arabic',
    'Name_Of_subcategory_in_arabic'           => 'Name of subcategory in arabic',
    'Name_Of_service_in_arabic'               => 'Name of service in arabic',
    'Name_Of_client_in_arabic'                => 'Name of client in arabic',
    'Name_Of_admin_in_arabic'                 => 'Name of admin in arabic',
    'Enter name of category in arabic'        => 'Enter name of category in arabic',
    'Enter name of service in arabic'         => 'Enter name of service in arabic',
    'Enter name of subcategory in arabic'     => 'Enter name of subcategory in arabic',
    'Enter name of driver in arabic'          => 'Enter name of driver in arabic',
    'Enter name of laundry worker in arabic'  => 'Enter name of laundry worker in arabic',
    'Enter email of driver'                   => 'Enter email of driver',
    'Enter email of laundry worker'           => 'Enter email of laundry worker',
    'Enter phone of driver'                   => 'Enter phone number of driver',
    'Enter phone of laundry worker'           => 'Enter phone number of laundry worker',
    'Enter password of driver'                => 'Enter password of driver',
    'Enter password of laundry worker'        => 'Enter password of laundry worker',
    'Enter birth date of driver'              => 'Enter birth date of driver',
    'Enter birth date of laundry worker'      => 'Enter birth date of laundry worker',
    'Category'                                => 'Category:',
    'Enter price of Subcategory'              => 'Enter price of Subcategory',
    'Price of Subcategory'                    => 'Price of Subcategory',
    'Add new Subcategory'                     => 'Add New Subcategory',
    'you_can_not_cancel_your_order_now'       => 'You can not cancel your order now',

    'Category_ID'                     => 'Category ID',
    'Category_Name'                   => 'Category Name',
    'Control'                         => 'Control',
    'Delete'                          => 'Delete',

    'Driver_ID'                          => 'Driver ID',
    'Driver_Name'                        => 'Driver Name',
    'Driver_Email'                       => 'Driver Email',
    'Driver_Phone'                       => 'Driver Phone Number',

    'Laundry_Worker_ID'                  => 'Laundry Worker ID',
    'Laundry_Worker_Name'                => 'Laundry Worker Name',
    'Laundry_Worker_Email'               => 'Laundry Worker Email',
    'Laundry_Worker_PhoneNumber'         => 'Laundry Worker Phone Number',

    'Subcategory_ID'            => 'Subcategory ID',
    'Service_ID'                => 'Service ID',
    'Subcategory_Name'          => 'Subcategory Name',
    'Service_Name'              => 'Service Name',
    'Subcategory_Price'         => 'Subcategory Price',
    'Change order status to'    => 'Change order status to',
    'Enter your name in arabic' => 'Enter your name in arabic',
    'Select_type_of_Service'    => 'Select the type of Service',
    'Select the subcategory:'   => 'Select the subcategory:',
    'Enter your Address:'       => 'Enter your Address:',
    'Submit Order'              => 'Submit Order',
    'client_login'              => 'Client Log in',
    'All_filed_have_(*)_required!'  => 'All filed have (*) required!',

    'cancel'             => 'cancel',
    'preparing'          => 'preparing',
    'ready_to_received'  => 'ready_to_received',
    'picked-up'          => 'picked-up',
    'delivered'          => 'delivered',
    'submit'             => 'submit',
    'on-delivery'        => 'on-delivery',




);
